### ISSUE TITLE
issue with only 0 as minterms for simplify

### ISSUE THREAD

**Issue by diatorker** [tpircher/quine-mccluskey#2]
if i use only the minterm 0 for the simplify function, it raise an indexError exception from the permutation function.
Here is the stack trace :
 _>>>qm.simplify([0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "qm.py", line 125, in simplify
    return self.simplify_los(ones, dc)
  File "qm.py", line 185, in simplify_los
    essential_implicants = self.__get_essential_implicants(prime_implicants)
  File "qm.py", line 409, in __get_essential_implicants
    perms[t] = set(p for p in self.permutations(t))
  File "qm.py", line 409, in <genexpr>
    perms[t] = set(p for p in self.permutations(t))
  File "qm.py", line 519, in permutations
    if value[i] == '0' or value[i] == '1':
IndexError: string index out of range_

Nice module, by the way ;)

**Comment by diatorker** [comment]
I found the answer. The problem come from the moment when the _simplify()_ function calculate the number of bits to use. because 0 is 0b0000, the number of bits to use is 0, so, _value_ become an empty string and _value[i]_. doesn't exist.

A way to overcome that can be to use a_nomber of bits_ argument which, if set, become the number of bits to use. This also overcome an other issue that I spoted later : because you can't set the number of signal, if you have two minterms like 6(_0b0110_) and 7(_0b0111_), the correct answer would be _['011-]_ but _simplify([6, 7])_ return _['11-']_

I already applied this solution to the script and now it works really well !

**Comment by tpircher** [comment]
Hi diatorker, thanks for the feeed-back. Commit 135c276 should hopefully address this issue. If not, please don't hesitate to re-open this bug.
Cheers!
