### ISSUE TITLE
Nonoptimal simplification

### ISSUE THREAD

**Issue by shizhouxing** [tpircher/quine-mccluskey#3]
Code:
```
a=qm.QuineMcCluskey()
print a.simplify([3,4,5,7,9,13,14,15])
```

Output:
```
set(['-1-1', '010-', '1-01', '111-', '0-11'])
```

But the first item `-1-1` seems to be redundant

**Comment by tpircher** [comment]
Yes, the code does not implement Petrick's method, and therefore the solution is not minimal.

**Comment by rsanden** [comment]
I needed this functionality and your implementation's handling XOR/XNOR is a key feature. After not finding any alternatives, I went ahead and wrote a minimizer -- diff attached. It's not performant, nor well-tested, but it meets my particular need and I'm including it here in case it's useful to anyone else.

[qm.py-135c276a.diff.txt](https://github.com/tpircher/quine-mccluskey/files/2129982/qm.py-135c276a.diff.txt)

**Comment by rsanden** [comment]
I needed better reduction with XOR functionality. All of the included tests pass, as well as these new ones:
```
# Sometimes fails returns {'^^--', '--^^'} instead of {'^^^^'}
{ 'res': set(['^^^^']), 'ons': [1, 7, 8, 14], 'dnc': [2, 4, 5, 6, 9, 10, 11, 13] },

# Test for QuineMcCluskey(use_xor = False)
{ 'res': set(['010-', '1-01', '111-', '0-11']), 'ons': [3,4,5,7,9,13,14,15] },
```

This is not rigorously tested and it's certainly slower. It's also somewhat outside the scope of pure QM - so I'm not planning to submit a pull request. However, I've attached a diff to qm.py at commit 135c276a in case it's useful to anyone.

[qm.py-135c276a.diff.txt](https://github.com/tpircher/quine-mccluskey/files/2130012/qm.py-135c276a.diff.txt)
