### ISSUE TITLE
ModuleNotFoundError: No module named 'qm' -- when installing with pip3

### ISSUE THREAD

**Issue by maehw** [tpircher/quine-mccluskey#9]
Hi!

First of all, thank you very much for providing your Python implementation of the Quine McCluskey algorithm publicly and making it open source! 🎉 

### The context

TL;DR: If context is irrelevant for you, directly go to "The Problem".

I based some work on your implementation. 
Some days ago, I stumbled across the TinyTapeout project (see https://github.com/mattvenn/tinytapeout-mpw7 and https://tinytapeout.com/) led by @mattvenn.

> TinyTapeout is an educational project that aims to make it easier and cheaper than ever to get your digital designs manufactured on a real chip!

Matt has partnered with @urish who runs [wokwi.com – Simulate IoT Projects in Your Browser
](https://wokwi.com/).

> Wokwi is an online Electronics simulator. You can use it to simulate Arduino, ESP32, and many other popular boards, parts and sensors.

So what you could do is,

1. start with a [wokwi template](https://wokwi.com/projects/339800239192932947), add your digital design in an easy-to-use framework/IDE,
1. create your TinyTapeout submission git repository from one of Matt's templates,
1. add the Wokwi project ID in your project and
1. trigger the GitHub Actions CI pipeline
1. ***wait while magic happens***
1. get your ASIC design.

Okay, that may be a bit simplified - but that's the basic idea from my point of view.

### The Idea

So my idea was to build a generator tool which takes truth tables (lookup table) as inputs and creates a Wokwi schematic with a lot of AND and OR gates automatically. This could lower the bar once again and make the implementation of simple designs with pure combinatorial logic even easier - but less tedious and error-prone.

There are some reasons now that I wanted to add Quine McCluskey algorithm:

Building up that lookup table would not require too much intelligence as you could just generate a matrix of AND and OR gates and add connections where required. This would generate a working schematic - but not clear at all. And it's fun to learn something new. 

### The Problem(s)

I am using Python3 and I am not a Python expert - I know the internals to little.

I've installed your module using pip: `pip3 install quine-mccluskey`

But than it cannot be found when importing it. Actually I don't know why as I am used to working modules just out of the box after having used pip.

The module can be found inside `/usr/local/lib/python3.10/site-packages/quine_mccluskey` on my machine (`pip3 list -v`). So the current workaround is to move the Python script there and execute it from there (ugly, true).

What is a more clear approach to address this? I am not sure if your module was written to be installed with pip, but it's listed here: https://pypi.org/project/quine-mccluskey/

I am also not sure if it's Python3 compatible as I can spot "python2.7" in your README.md. But, it seems to run.

*Side note: It seems that your implementation does not give deterministic results, but that's already addressed in #8.*

**Comment by mattvenn** [comment]
One thing to note is that any gates you generate in wokwi will be subject to optimisation later in the ASIC flow.

**Comment by gatecat** [comment]
I think `from quine_mccluskey import qm` should work, it seems to for me

**Comment by maehw** [comment]
> `from quine_mccluskey import qm`

Great, that does the trick. 😄 Thanks! 
Could you maybe elaborate with a short, newbie-friendly answer?

**Comment by gatecat** [comment]
There are probably some details I'm missing out but essentially Python follows a series of rules for looking up modules. Paths it searches by default are things like `/usr/local/lib/python3.10/site-packages/` and the current directory (actually a bit more complex than that but let's ignore for now). Other paths can be added with the `PYTHONPATH` environment variable.

In this case `qm` doesn't exist in any of those paths so it won't be found. But `quine_mccluskey` does exist, and within it is the submodule `qm`, `from quine_mccluskey import qm` tells Python how to find `qm`.

**Comment by maehw** [comment]
Thanks @gatecat.
That resolves the issue!
